Updating content
- Updating deprecated syntax:
```
λ gcloud compute instances create chef-server --image centos-6 --zone
us-central1-b --machine-type n1-standard-1 --scopes compute-rw
storage-full
WARNING: We noticed that you are using space-separated lists, which are
deprecated. Please transition to using comma-separated lists instead
(try "--scopes compute-rw,storage-full"). If you intend to use
[storage-full] as positional arguments, put the flags at the end.
Created
[https://www.googleapis.com/compute/v1/projects/myproject/zones/us-central1-b/instances/chef-server].
NAME        ZONE          MACHINE_TYPE  PREEMPTIBLE INTERNAL_IP
EXTERNAL_IP   STATUS
chef-server us-central1-b n1-standard-1             10.240.xx.xx
104.154.xx.xx RUNNING
λ gcloud compute instances create chef-server --image centos-6 --zone
us-central1-b --machine-type n1-standard-1 --scopes
compute-rw,storage-full
Created
[https://www.googleapis.com/compute/v1/projects/myproject/zones/us-central1-b/instances/chef-server].
NAME        ZONE          MACHINE_TYPE  PREEMPTIBLE INTERNAL_IP
EXTERNAL_IP   STATUS
chef-server us-central1-b n1-standard-1             10.240.135.118
104.197.xx.xx RUNNING
```
- Updated to newest Chef 11 package. (This really should be updated to
  Chef12, but it's a lot of work...)
- Chef install link now leads to client, added a proper link to server.
- The documentation links for Chef were leading nowhere, I re-pointed
  them, however, note, that there is no more login section in there. I
strongly suspect they wanted to remove all traces of default login:pw
from docs.
- `firewalls` section no longer exists:
```
λ gcloud compute firewalls create allow-https --allow=tcp:443
...
ERROR: (gcloud.compute) Invalid choice: 'firewalls'. Did you mean
'firewall-rules'?

λ gcloud compute firewall-rules create allow-https --allow=tcp:443
(2)
Created
[https://www.googleapis.com/compute/v1/projects/myproject/global/firewalls/allow-https].
NAME        NETWORK SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
allow-https default 0.0.0.0/0  tcp:443
```
- `get` is now `list`:
```
λ gcloud compute instances get chef-server
...

ERROR: (gcloud.compute.instances) Invalid choice: 'get'. Did you mean
'list'?

λ gcloud compute instances list chef-server
NAME        ZONE          MACHINE_TYPE  PREEMPTIBLE INTERNAL_IP
EXTERNAL_IP   STATUS
chef-server us-central1-b n1-standard-1             10.240.135.118
104.197.82.28 RUNNING
```
- The referenced Debian image no longer exists:
```
λ gcloud compute instances create chef-workstation --image
debian-cloud/global/images/debian-7-v20140606 --zone us-central1-b
--machine-type n1-standard-1 --scopes compute-rw,storage-full
ERROR: (gcloud.compute.instances.create) wrong number of fields:
[debian-cloud/global/images/debian-7-v20140606] does not match any of
IMAGE, /PROJECT/IMAGE

λ gcloud compute instances create chef-workstation --image debian-7
--zone us-central1-b --machine-type n1-standard-1 --scopes
compute-rw,storage-full
Created
[https://www.googleapis.com/compute/v1/projects/myproject/zones/us-central1-b/instances/chef-workstation].
NAME             ZONE          MACHINE_TYPE  PREEMPTIBLE INTERNAL_IP
EXTERNAL_IP  STATUS
chef-workstation us-central1-b n1-standard-1             10.240.xx.xx
108.59.xx.xx RUNNING
```
- Chef quick install will install 12x client, which is incompatible with
  the instructions.